spring:
    application:
        name: Random Saying
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        #show-sql: true
    datasource:
        url: jdbc:sqlite:database.db
        driver-class-name: org.sqlite.JDBC
